name: CI
on: ["push", "pull_request"]

env:
  FORCE_COLOR: 1
  EARTHLY_STRICT: "true"
  PUSH: "${{ github.repository_owner == 'andyli' && github.event_name == 'push' }}"

jobs:
  job:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Login to GitHub Container Registry
        if: success() && env.PUSH == 'true'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Specify Earthly remote cache
        run: echo "EARTHLY_REMOTE_CACHE=ghcr.io/andyli/pyextern_cache:$(echo "$GITHUB_REF_NAME" | sed 's/[^A-Za-z0-9\-\.]/_/g')" >> $GITHUB_ENV
      - name: Setup Earthly
        run: "sudo /bin/sh -c 'curl -fsSL https://github.com/earthly/earthly/releases/download/v0.6.7/earthly-linux-amd64 -o /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - name: Build devcontainer
        run: earthly +ci-images --GIT_REF_NAME="${{ github.ref_name }}" --GIT_SHA="${{ github.sha }}"
        env:
          EARTHLY_PUSH: ${{ env.PUSH }}
      - name: Generate externs of core dependencies
        run: earthly +gen-coredep
